AllCops:
  Exclude:
    - 'bin/**/*'
  TargetRubyVersion: 2.4
Rails:
  Enabled: true
Rails/ReversibleMigration:
  Enabled: false
AsciiComments:
  Enabled: false
Layout/IndentArray:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
ParameterLists:
  CountKeywordArgs: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
CyclomaticComplexity:
  Max: 13
PerceivedComplexity:
  Max: 13
Metrics/ClassLength:
  Max: 300
